In [1]:
import pandas as pd
# Load the dataset
df = pd.read_csv("HR Data.csv")
# Remove unnecessary columns
columns_to_drop = ['EmployeeCount', 'StandardHours', 'Over18', 'EmployeeNumber']
df_cleaned = df.drop(columns=columns_to_drop)

In [4]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

1. Removing Unnecessary Columns

In [5]:
columns_to_drop = ['EmployeeCount', 'StandardHours', 'Over18', 'EmployeeNumber']
df_cleaned = df.drop(columns=columns_to_drop)

In [6]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

2.Rename columns

In [15]:
# Rename columns (example of a few columns, adjust as necessary)
rename_columns = {
    'Attrition': 'Employee Attrition',
    'BusinessTravel': 'Travel Frequency',
    'DailyRate': 'Daily Rate',
    'DistanceFromHome': 'Distance From Home',
    'EducationField': 'Field of Education',
    'JobRole': 'Job Role'
}
df_cleaned.rename(columns=rename_columns, inplace=True)
df_cleaned.head()

,Age,Daily Rate,Distance From Home,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,Job Role_Manufacturing Director,Job Role_Research Director,Job Role_Research Scientist,Job Role_Sales Executive,Job Role_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,41,1102.0,1,2,2,94.0,3,2,4,-0.108313,...,False,False,False,True,False,False,False,True,False,True
1,49,279.0,8,1,3,61.0,2,2,2,-0.291619,...,False,False,True,False,False,False,True,False,True,False
2,37,1373.0,2,2,4,92.0,2,1,3,-0.937335,...,False,False,False,False,False,False,False,True,False,True
3,33,1392.0,3,4,4,56.0,3,1,3,-0.763374,...,False,False,True,False,False,False,True,False,False,True
4,27,591.0,2,1,1,40.0,3,1,2,-0.644639,...,False,False,False,False,False,False,True,False,True,False

3. Eliminating Redundant Entries

In [8]:
# Eliminate redundant entries
df_cleaned.drop_duplicates(inplace=True)

4. Sanitizing Specific Columns

In [9]:
# Sanitize specific columns (ensuring categorical consistency)
df_cleaned['Employee Attrition'] = df_cleaned['Employee Attrition'].str.strip().str.capitalize()
df_cleaned['OverTime'] = df_cleaned['OverTime'].str.strip().str.capitalize()

5. Eliminating NaN Values

In [13]:
# Check for null values in the dataset
null_values = df.isnull().sum()
null_values

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [14]:
#Handle missing values by dropping rows with NaN values
df_cleaned.dropna(inplace=True)
df_cleaned

,Age,Daily Rate,Distance From Home,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,Job Role_Manufacturing Director,Job Role_Research Director,Job Role_Research Scientist,Job Role_Sales Executive,Job Role_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,41,1102.0,1,2,2,94.0,3,2,4,-0.108313,...,False,False,False,True,False,False,False,True,False,True
1,49,279.0,8,1,3,61.0,2,2,2,-0.291619,...,False,False,True,False,False,False,True,False,True,False
2,37,1373.0,2,2,4,92.0,2,1,3,-0.937335,...,False,False,False,False,False,False,False,True,False,True
3,33,1392.0,3,4,4,56.0,3,1,3,-0.763374,...,False,False,True,False,False,False,True,False,False,True
4,27,591.0,2,1,1,40.0,3,1,2,-0.644639,...,False,False,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884.0,23,2,3,41.0,4,2,4,-0.835167,...,False,False,False,False,False,False,True,False,True,False
1466,39,613.0,6,1,4,42.0,2,3,1,0.740888,...,False,False,False,False,False,False,True,False,True,False
1467,27,155.0,4,3,2,87.0,4,2,2,-0.076664,...,True,False,False,False,False,False,True,False,False,True
1468,49,1023.0,2,3,4,63.0,2,2,2,-0.236394,...,False,False,False,True,False,False,True,False,True,False
1469,34,628.0,8,3,2,82.0,4,2,3,-0.445826,...,False,False,False,False,False,False,True,False,True,False


Here are a few additional changes that could be necessary:
Ensure Correct Data Types: Ensure columns have appropriate data types.
Normalize/Standardize Numerical Columns: Normalize numerical columns if preparing for machine learning.
Categorical Encoding: Convert categorical columns to numeric using one-hot encoding.

In [11]:
# Ensure correct data types
df_cleaned['Age'] = df_cleaned['Age'].astype(int)
df_cleaned['Daily Rate'] = df_cleaned['Daily Rate'].astype(float)
df_cleaned['Distance From Home'] = df_cleaned['Distance From Home'].astype(int)
df_cleaned['Education'] = df_cleaned['Education'].astype(int)
df_cleaned['EnvironmentSatisfaction'] = df_cleaned['EnvironmentSatisfaction'].astype(int)
df_cleaned['HourlyRate'] = df_cleaned['HourlyRate'].astype(float)
df_cleaned['JobInvolvement'] = df_cleaned['JobInvolvement'].astype(int)
df_cleaned['JobLevel'] = df_cleaned['JobLevel'].astype(int)
df_cleaned['JobSatisfaction'] = df_cleaned['JobSatisfaction'].astype(int)
df_cleaned['MonthlyIncome'] = df_cleaned['MonthlyIncome'].astype(float)
df_cleaned['MonthlyRate'] = df_cleaned['MonthlyRate'].astype(float)
df_cleaned['NumCompaniesWorked'] = df_cleaned['NumCompaniesWorked'].astype(int)
df_cleaned['PercentSalaryHike'] = df_cleaned['PercentSalaryHike'].astype(int)
df_cleaned['PerformanceRating'] = df_cleaned['PerformanceRating'].astype(int)
df_cleaned['RelationshipSatisfaction'] = df_cleaned['RelationshipSatisfaction'].astype(int)
df_cleaned['StockOptionLevel'] = df_cleaned['StockOptionLevel'].astype(int)
df_cleaned['TotalWorkingYears'] = df_cleaned['TotalWorkingYears'].astype(int)
df_cleaned['TrainingTimesLastYear'] = df_cleaned['TrainingTimesLastYear'].astype(int)
df_cleaned['WorkLifeBalance'] = df_cleaned['WorkLifeBalance'].astype(int)
df_cleaned['YearsAtCompany'] = df_cleaned['YearsAtCompany'].astype(int)
df_cleaned['YearsInCurrentRole'] = df_cleaned['YearsInCurrentRole'].astype(int)
df_cleaned['YearsSinceLastPromotion'] = df_cleaned['YearsSinceLastPromotion'].astype(int)
df_cleaned['YearsWithCurrManager'] = df_cleaned['YearsWithCurrManager'].astype(int)

# Normalize/Standardize numerical columns (example for 'MonthlyIncome')
df_cleaned['MonthlyIncome'] = (df_cleaned['MonthlyIncome'] - df_cleaned['MonthlyIncome'].mean()) / df_cleaned['MonthlyIncome'].std()

# Convert categorical columns to numeric if preparing for machine learning
df_cleaned = pd.get_dummies(df_cleaned, columns=['Employee Attrition', 'Travel Frequency', 'Department', 'Field of Education', 'Gender', 'Job Role', 'MaritalStatus', 'OverTime'])

df_cleaned.head()

,Age,Daily Rate,Distance From Home,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,Job Role_Manufacturing Director,Job Role_Research Director,Job Role_Research Scientist,Job Role_Sales Executive,Job Role_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,41,1102.0,1,2,2,94.0,3,2,4,-0.108313,...,False,False,False,True,False,False,False,True,False,True
1,49,279.0,8,1,3,61.0,2,2,2,-0.291619,...,False,False,True,False,False,False,True,False,True,False
2,37,1373.0,2,2,4,92.0,2,1,3,-0.937335,...,False,False,False,False,False,False,False,True,False,True
3,33,1392.0,3,4,4,56.0,3,1,3,-0.763374,...,False,False,True,False,False,False,True,False,False,True
4,27,591.0,2,1,1,40.0,3,1,2,-0.644639,...,False,False,False,False,False,False,True,False,True,False